# Generated by Django 6.1.1 on 2026-09-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_number', models.CharField(max_length=50, verbose_name='Номер счётчика')),
                ('reading_date', models.DateField(verbose_name='Дата показания')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Показание, м³')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Показание счётчика',
                'verbose_name_plural': 'Показания счётчиков',
                'ordering': ['-reading_date'],
            },
        ),
    ]
